name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd cli
          yarn
      - name: Check formatting
        run: |
          cd cli
          yarn test:format
      - name: Run tests
        run: |
          cd cli
          yarn test:unit
