name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd cli
          npm install
      - name: Check formatting
        run: |
          cd cli
          npm run test:format
  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd web
          npm install --legacy-peer-deps
      - name: Check formatting
        run: |
          cd web
          npm run test:format
      - name: Run tests
        run: |
          cd web
          npm run test:unit
