name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd cli
          npm install
      - name: Run tests
        run: |
          cd cli
          npm run test
